version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: stock-concurrency-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: foo
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./src/main/resources/db/migration/create_table.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: stock-concurrency-redis
    ports:
      - "6379:6379"
    command: redis-server --maxmemory-policy noeviction
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
